name: Build and Test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  industrial_ci:
    strategy:
      fail-fast: false
      matrix:
        env:
          - ROS_DISTRO: jazzy
          - ROS_DISTRO: humble
          - ROS_DISTRO: rolling

    env:
      CCACHE_DIR: /github/home/.ccache
      ROS_REPO: main

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # This step will fetch/store the directory used by ccache before/after the ci run
      - uses: actions/cache@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-{{ matrix.env.ROS_DISTRO }}-{{ matrix.env.ROS_REPO }}
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{ matrix.env }}
